# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.54/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: page
  display: shell
  authorization:
    allowAll: true
  content:
    - component: Text
      name: markdown
      props:
        mode: text
        value: Supprimer une sous-tâche
        variant: h1
      layout:
        horizontalAlign: center
    - component: Text
      name: markdown2
      props:
        mode: text
        value: 1)- Sélectionnez un ID de tâche
        variant: subtitle2
    - component: DataGrid
      name: dataGrid
      layout:
        height: 192.00001525878906
      props:
        rows:
          $$jsExpression: donnerIDTaches.data
        columns:
          - field: id
            type: number
          - field: titre
            type: string
          - field: complete
            type: boolean
    - component: PageRow
      name: pageRow1
      props:
        justifyContent: start
      children:
        - component: Text
          name: markdown1
          props:
            mode: text
            value: 2)- Sélectionnez un ID de sous-tâche et cliquez sur 'Supprimer' ->
            variant: subtitle2
        - component: Button
          name: button
          props:
            content: Supprimer
            size: medium
            onClick:
              $$jsExpressionAction: supprimerSousTacheQuery.call()
            fullWidth: true
        - component: Button
          name: button2
          props:
            content: Refresh
            size: medium
            onClick:
              $$jsExpressionAction: donnerSousTaches.refetch()
            fullWidth: true
            color: secondary
    - component: Text
      name: markdown3
      props:
        mode: text
        value:
          $$jsExpression: supprimerSousTacheQuery.data
      layout:
        horizontalAlign: end
    - component: DataGrid
      name: dataGrid1
      layout:
        height: 232
      props:
        rows:
          $$jsExpression: donnerSousTaches.data
        columns:
          - field: titre_sous_tache
            type: string
          - field: complete_sous_tache
            type: boolean
    - component: Button
      name: button1
      props:
        variant: text
        color: secondary
        content: Retour au menu principal
        onClick:
          $$navigationAction:
            page: projet_session
            parameters: {}
  queries:
    - name: supprimerSousTacheQuery
      mode: mutation
      query:
        kind: rest
        url:
          $$jsExpression:
            "`${parameters.api_host}/api/liste_taches/sous_tache/${paramete\
            rs.id_sous_tache}`"
        headers:
          - name: Authorization
            value:
              $$env: API_KEY
        method: DELETE
        searchParams: []
        transform: return data.message;
        transformEnabled: true
      parameters:
        - name: id_sous_tache
          value:
            $$jsExpression: dataGrid1.selection.id_sous_tache
        - name: Authorization
          value:
            $$env: API_KEY
        - name: api_host
          value:
            $$env: API_HOST
    - name: donnerSousTaches
      mode: query
      query:
        kind: rest
        url:
          $$jsExpression:
            "`${parameters.api_host}/api/liste_taches/detail/${parameters.i\
            d_tache}`"
        headers:
          - name: Authorization
            value:
              $$env: API_KEY
        method: GET
        transform: return data.result.taches[0].sous_taches;
        transformEnabled: true
        searchParams: []
      parameters:
        - name: id_tache
          value:
            $$jsExpression: dataGrid.selection.id
        - name: Authorization
          value:
            $$env: API_KEY
        - name: api_host
          value:
            $$env: API_HOST
    - name: donnerIDTaches
      mode: query
      query:
        kind: rest
        url:
          $$jsExpression: "`${parameters.api_host}/api/liste_taches/all`"
        headers:
          - name: Authorization
            value:
              $$env: API_KEY
        method: GET
        transform: return data.result;
        transformEnabled: true
        searchParams: []
      parameters:
        - name: Authorization
          value:
            $$env: API_KEY
        - name: api_host
          value:
            $$env: API_HOST
