# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.54/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Ajouter une tâche
  content:
    - component: Text
      name: markdown
      layout:
        horizontalAlign: center
      props:
        mode: text
        value: Ajouter une tâche
        variant: h1
    - component: PageRow
      name: pageRow3
      props:
        justifyContent: start
      children:
        - component: Text
          name: markdown2
          props:
            mode: text
            value: Titre de la tâche
            variant: h6
        - component: TextField
          name: textField1
          props:
            fullWidth: true
            isRequired: true
    - component: PageRow
      name: pageRow2
      props:
        justifyContent: start
      children:
        - component: Text
          name: markdown3
          props:
            mode: text
            value: Description
            variant: h6
        - component: TextField
          name: textField2
          props:
            fullWidth: true
            isRequired: true
    - component: PageRow
      name: pageRow1
      props:
        justifyContent: start
      children:
        - component: Text
          name: markdown4
          props:
            mode: text
            value: Date de début
            variant: h6
        - component: DatePicker
          name: datePicker
          props:
            fullWidth: true
            isRequired: true
            defaultValue:
              $$jsExpression: '"10/04/2023"'
    - component: PageRow
      name: pageRow4
      props:
        justifyContent: start
      children:
        - component: Text
          name: markdown5
          props:
            mode: text
            value: Date d'échéance
            variant: h6
        - component: DatePicker
          name: datePicker1
          props:
            fullWidth: true
            isRequired: true
            defaultValue:
              $$jsExpression: '"10/04/2024"'
    - component: PageRow
      name: pageRow5
      props:
        justifyContent: start
      children:
        - component: Text
          name: markdown6
          props:
            mode: text
            value: Statut de la tâche
            variant: h6
        - component: Select
          name: select1
          props:
            fullWidth: true
            defaultValue:
              $$jsExpression: '"false"'
            isRequired: true
            options:
              - "true"
              - "false"
    - component: PageRow
      name: pageRow6
      props:
        justifyContent: start
      children:
        - component: Button
          name: button
          props:
            size: large
            content: Enregistrer
            onClick:
              $$jsExpressionAction: ajouterTacheQuery.call()
        - component: Text
          name: markdown7
          props:
            mode: text
            value:
              $$jsExpression: ajouterTacheQuery.data.message
            variant: h5
          layout:
            horizontalAlign: end
            verticalAlign: center
    - component: PageRow
      name: pageRow
      props:
        justifyContent: start
      children:
        - component: Text
          name: markdown1
          props:
            mode: text
            value:
              $$jsExpression: "`Tableau de tâches`"
            variant: h6
        - component: Button
          name: button2
          props:
            size: small
            content: Refresh
            onClick:
              $$jsExpressionAction: afficherToutesTaches.refetch()
            color: secondary
          layout:
            verticalAlign: center
            horizontalAlign: center
    - component: DataGrid
      name: dataGrid
      props:
        rows:
          $$jsExpression: afficherToutesTaches.data
        columns:
          - field: id
            type: number
          - field: titre
            type: string
            width: 339
          - field: complete
            type: boolean
      layout:
        height: 220
    - component: Button
      name: button1
      props:
        content: Retour au menu principal
        color: secondary
        variant: text
        onClick:
          $$navigationAction:
            page: projet_session
            parameters: {}
  display: shell
  authorization:
    allowAll: true
  queries:
    - name: ajouterTacheQuery
      mode: mutation
      query:
        kind: rest
        url:
          $$jsExpression: "`${parameters.api_host}/api/liste_taches/tache`"
        headers: [{ name: Authorization, value: { $$env: API_KEY } }]
        method: POST
        searchParams: []
        body:
          kind: raw
          content:
            $$jsExpression: "`{\r

              \    \"titre_tache\":\"${parameters.titre_tache}\",\r

              \    \"description\":\"${parameters.description}\",\r

              \    \"date_debut\":\"${parameters.date_debut}\",\r

              \    \"date_echeance\":\"${parameters.date_echeance}\",\r

              \    \"complete_tache\":${parameters.complete_tache}\r

              }`"
          contentType: application/json
      parameters:
        - name: titre_tache
          value:
            $$jsExpression: textField1.value
        - name: description
          value:
            $$jsExpression: textField2.value
        - name: date_debut
          value:
            $$jsExpression: datePicker.value
        - name: date_echeance
          value:
            $$jsExpression: datePicker1.value
        - name: complete_tache
          value:
            $$jsExpression: select1.value
        - name: Authorization
          value:
            $$env: API_KEY
        - name: api_host
          value:
            $$env: API_HOST
    - name: afficherToutesTaches
      mode: query
      query:
        kind: rest
        url:
          $$jsExpression: "`${parameters.api_host}/api/liste_taches/all`"
        headers:
          - name: Authorization
            value:
              $$env: API_KEY
        method: GET
        searchParams: []
        transform: return data.result;
        transformEnabled: true
      parameters:
        - name: Authorization
          value:
            $$env: API_KEY
        - name: api_host
          value:
            $$env: API_HOST
